#!/bin/bash

# Проверка, находимся ли мы в git репозитории
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo "Ошибка: Текущая директория не является git репозиторием."
    exit 1
fi

echo "Забираем изменения из удаленного репозитория..."
# Выполняем pull
git pull

echo "Успешно обновлено!"
